services:
 db:
  image: mysql:9.1.0
  container_name: php_snh_db
  env_file: "env/db.env"
  ports:
   - "127.0.0.1:3306:3306"
  volumes:
   - ./db:/var/lib/mysql

 app:
  image: php_snh
  build: .
  container_name: php_snh_app
  env_file: "env/app.env"
  volumes:
   - ./app:/var/www/html/
  ports:
   - "127.0.0.1:8080:80"
  depends_on:
   - db
  links:
   - db
  tty: true
