services:
 db:
  image: mysql:9.1.0
  container_name: snh_db
  env_file: database/db.env
  ports:
   - '127.0.0.1:3306:3306'
  volumes:
   - db_volume:/var/lib/mysql
  healthcheck:
   test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
   start_period: 5s
   interval: 5s
   timeout: 5s
   retries: 4

 app:
  build: 
    context: .
    args:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      APACHE_APP_ROOT: /var/www/html
  container_name: snh_app
  env_file: app/app.env
  ports:
   - '127.0.0.1:8080:80'
   - '127.0.0.1:8443:443'
  depends_on:
    db:
      condition: service_healthy
  develop:
    watch:
      - action: sync
        path: ./app
        target: /var/www/html
        ignore:
          - libs/composer.json
          - public/.htaccess
      - action: rebuild
        path: ./app/libs/composer.json
      - action: rebuild
        path: ./app/public/.htaccess
  tty: true

volumes:
  db_volume: