services:
 db:
  build: 
    context: ./database
  container_name: snh_db
  env_file: database/db.env
  ports:
   - '127.0.0.1:3306:3306'
  volumes:
   - db_data:/var/lib/mysql
   - db_keyring:/var/lib/mysql-keyring
  healthcheck:
   test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
   start_period: 5s
   interval: 5s
   timeout: 5s
   retries: 4

 app:
  build: 
    context: ./app
    args:
      EVASIVE_MOD: yes
  container_name: snh_app
  env_file: app/app.env
  ports:
   - '127.0.0.1:443:443'
  volumes:
   - app_uploads:/var/www/html/uploads
  depends_on:
    db:
      condition: service_healthy
  develop:
    watch:
      - action: sync
        path: ./app/src
        target: /var/www/html
        ignore:
          - libs/composer.json
          - public/.htaccess
      - action: rebuild
        path: ./app/src/libs/composer.json
      - action: rebuild
        path: ./app/src/public/.htaccess
  tty: true

volumes:
  db_data:
  db_keyring:
  app_uploads: